### ISSUE TITLE
Database Error 

### ISSUE THREAD

**Issue by haroldfries** [rudiliu/simple-login-CI#5]
![image](https://user-images.githubusercontent.com/31174422/29492092-2878e06c-85a3-11e7-9095-55dae379bd33.png)

**Comment by rudiliu** [comment]
move activity_logs table query after user

**Comment by haroldfries** [comment]
Still its error. Can you have a new file of its db?

**Comment by haroldfries** [comment]
I still have an error sir. 
![image](https://user-images.githubusercontent.com/31174422/29501368-b3d660b4-865a-11e7-8dab-849cc98fcc21.png)

**Comment by lea55** [comment]
As I solve this error you could pass some capture of the solution or upload the project again thanks
