### ISSUE TITLE
Does not work in Cpanel Hosting Like ehost.usa.cc or 000.webhost.com

### ISSUE THREAD

**Issue by akon6305** [rudiliu/simple-login-CI#6]
Hey Brother! 
I am grateful to you. I have learn a lot from your project.

It work well on wamp server but not working with Cpanel hosing site. When I Upload my project on C panel it does not send any email but other functin works well.

If you kindly help me I will be very happy please help me. Please.......

**Comment by rudiliu-ds** [comment]
if you are using gmail, it's probable the security issue.
try out this: https://support.google.com/mail/answer/7126229?hl=en&visit_id=1-636403145388865840-2496538333&rd=1#cantsignin

**Comment by rudiliu** [comment]
if you are using gmail, it's probable the security issue.

try out this: https://support.google.com/mail/answer/7126229?hl=en&visit_id=1-636403145388865840-2496538333&rd=1#cantsignin

especially this step:
https://support.google.com/accounts/answer/6010255
and
https://accounts.google.com/b/0/DisplayUnlockCaptcha

**Comment by akon6305** [comment]
Thanks for your kind information. It works on yahoo mail 

Thank you
