### ISSUE TITLE
getting error to the database can you send me another sql code for the same project 

### ISSUE THREAD

**Issue by anandlinast** [rudiliu/simple-login-CI#7]
![image](https://user-images.githubusercontent.com/31241271/30325979-88acf0c4-97e4-11e7-9aa8-ce9d55fe5462.png)

i have created db simple_login 

then importing the sql file from folder geeting this error

**Comment by rudiliu** [comment]
please read the past issues before posting a new one. 
It has been resolved here: https://github.com/rudiliu/simple-login-CI/issues/5
